// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5KDpgAzIpWTxsyApcr9vJhF3htXqCaXo',
    appId: '1:332498915207:web:cb768d14783d2f657c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    authDomain: 'sb-flutter-batch-60.firebaseapp.com',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
    measurementId: 'G-59Y2PJMN05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsX0THoZKpY8AmxvoVyabLkfL9vilJMY',
    appId: '1:332498915207:android:3f1d1abbf9dbb34b7c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU25q6e2sBZ__rU1J-rB9KGGbpYgeqZuE',
    appId: '1:332498915207:ios:45bafab5a16b724b7c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
    iosBundleId: 'com.example.tugas7FlutterIntro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU25q6e2sBZ__rU1J-rB9KGGbpYgeqZuE',
    appId: '1:332498915207:ios:45bafab5a16b724b7c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
    iosBundleId: 'com.example.tugas7FlutterIntro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5KDpgAzIpWTxsyApcr9vJhF3htXqCaXo',
    appId: '1:332498915207:web:853afddfcbe2e2827c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    authDomain: 'sb-flutter-batch-60.firebaseapp.com',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
    measurementId: 'G-WF8ZS53QV9',
  );
}
