// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5KDpgAzIpWTxsyApcr9vJhF3htXqCaXo',
    appId: '1:332498915207:web:06e90ab66672aa407c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    authDomain: 'sb-flutter-batch-60.firebaseapp.com',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
    measurementId: 'G-LTG7VN73FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsX0THoZKpY8AmxvoVyabLkfL9vilJMY',
    appId: '1:332498915207:android:0d4fbe7da075a4947c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU25q6e2sBZ__rU1J-rB9KGGbpYgeqZuE',
    appId: '1:332498915207:ios:e4cee913fc6c48ef7c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
    iosClientId: '332498915207-n168n7kuh2ovnsbqdf7unh94ajh6rbna.apps.googleusercontent.com',
    iosBundleId: 'com.sbflutterfinalproject.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU25q6e2sBZ__rU1J-rB9KGGbpYgeqZuE',
    appId: '1:332498915207:ios:e4cee913fc6c48ef7c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
    iosClientId: '332498915207-n168n7kuh2ovnsbqdf7unh94ajh6rbna.apps.googleusercontent.com',
    iosBundleId: 'com.sbflutterfinalproject.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5KDpgAzIpWTxsyApcr9vJhF3htXqCaXo',
    appId: '1:332498915207:web:19851ab0a11f8c6c7c4d22',
    messagingSenderId: '332498915207',
    projectId: 'sb-flutter-batch-60',
    authDomain: 'sb-flutter-batch-60.firebaseapp.com',
    storageBucket: 'sb-flutter-batch-60.appspot.com',
    measurementId: 'G-WC3W51VBSC',
  );
}
